[package]
name = "totality-gui"
version = "0.1.0"
authors = ["AlterionX <ben.benjamin.ben@gmail.com>"]
edition = "2018"

[dependencies]
totality-events = { path = "../totality-events" }
totality-model = { path = "../totality-model" }
quick-xml = "0.14.0"
lazy_static = "1.3.0"
log = "0.4.6"

