[package]
name = "totality-sync"
version = "0.1.0"
authors = ["AlterionX <ben.benjamin.ben@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_bench"
harness = false

