[package]
name = "totality-events"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.6"
[dependencies.na]
package = "nalgebra"
version = "0.29.0"
