[package]
name = "totality-model"
version = "0.1.0"
authors = ["AlterionX <ben.benjamin.ben@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
bytemuck = "1"
[dependencies.na]
package = "nalgebra"
version = "0.32"
features = ["convert-bytemuck"]
