[package]
name = "totality-shatter"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2021"

[dependencies]
totality-model = { path = "../totality-model" }
boomphf = "0.2.0"
log = "0.4.6"

[dependencies.nalgebra]
version = "0.32"
features = ["convert-bytemuck"]
