[package]
name = "totality-sim"
version = "0.1.0"
authors = ["AlterionX <ben.benjamin.ben@gmail.com>"]
edition = "2018"

[dependencies]
totality-threading = { path = "../totality-threading" }
totality-model = { path = "../totality-model" }
nalgebra = "0.18.0"
log = "0.4.6"

